apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microshop-ingress
  namespace: micro-shop
  annotations:
    # This is the only annotation you need. It tells Kubernetes to use the
    # NGINX Ingress controller that you have installed.
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # --- Backend API Rules ---
      # When the URL path starts with /api/users, send it to the user-service-svc
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service-svc
            port:
              number: 3001

      # When the URL path starts with /api/products, send it to the product-service-svc
      - path: /api/products
        pathType: Prefix
        backend:
          service:
            name: product-service-svc
            port:
              number: 3002

      # When the URL path starts with /api/orders, send it to the order-service-svc
      - path: /api/orders
        pathType: Prefix
        backend:
          service:
            name: order-service-svc
            port:
              number: 3003
      
      # --- Frontend Rule (Default/Catch-all) ---
      # When the URL path starts with /, send it to the frontend-svc
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-svc
            port:
              number: 80